"use client";

import { Copy, ExternalLink, Save } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { WorkspaceShell } from "./workspace-shell";
import { useWorkspace } from "./workspace-provider";

const API_URL = process.env.NEXT_PUBLIC_API_URL || "http://localhost:4000/v1";
const days = ["Domingo", "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado"];
type Config = { restaurant: { name: string; slug: string; profileImageUrl?: string | null; branches: Array<{ id: string; name: string; publicSlug: string; onlineBookingDurationMinutes: number }> }; settings: { isEnabled: boolean; coverImageUrl?: string | null; whatsappPhone?: string | null; accentColor: string; minAdvanceMinutes: number; maxAdvanceDays: number; minPartySize: number; maxPartySize: number }; schedules: Array<{ branchId: string; weekday: number; isEnabled: boolean; startTime: string; endTime: string; intervalMin: number }>; exceptions: Array<{ branchId: string; serviceDate: string; isClosed: boolean; startTime?: string | null; endTime?: string | null; intervalMin?: number | null }> };

export function OnlineBookingsPage() {
  const { token, currentUser } = useWorkspace();
  const [config, setConfig] = useState<Config | null>(null); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { if (!token) return; fetch(`${API_URL}/restaurant/online-booking`, { headers: { Authorization: `Bearer ${token}` } }).then(async (response) => { if (!response.ok) throw new Error("No se pudo cargar la configuracion"); return response.json() as Promise<Config>; }).then((data) => {
    const known = new Set(data.schedules.map((item) => `${item.branchId}:${item.weekday}`));
    const defaults = data.restaurant.branches.flatMap((branch) => days.map((_, weekday) => ({ branchId: branch.id, weekday, isEnabled: false, startTime: "12:00", endTime: "23:00", intervalMin: 30 })).filter((item) => !known.has(`${item.branchId}:${item.weekday}`)));
    setConfig({ ...data, schedules: [...data.schedules, ...defaults] });
  }).catch((reason) => setError(reason.message)); }, [token]);
  const publicUrl = useMemo(() => config ? `${window.location.origin}/reservar/${config.restaurant.slug}` : "", [config]);
  if (currentUser?.role !== "restaurant_owner") return <WorkspaceShell title="Reservas online" description="Configuracion de la pagina publica."><p>No tenes permiso para configurar reservas online.</p></WorkspaceShell>;
  if (!config) return <WorkspaceShell title="Reservas online" description="Configura tu pagina publica."><p>{error || "Cargando configuracion..."}</p></WorkspaceShell>;
  const updateSettings = (key: string, value: unknown) => setConfig((current) => current ? { ...current, settings: { ...current.settings, [key]: value } } : current);
  const updateSchedule = (branchId: string, weekday: number, key: string, value: unknown) => setConfig((current) => current ? { ...current, schedules: current.schedules.map((item) => item.branchId === branchId && item.weekday === weekday ? { ...item, [key]: value } : item) } : current);
  const addException = () => setConfig((current) => current ? { ...current, exceptions: [...current.exceptions, { branchId: current.restaurant.branches[0]?.id || "", serviceDate: new Date().toISOString().slice(0, 10), isClosed: true }] } : current);
  const updateException = (index: number, key: string, value: unknown) => setConfig((current) => current ? { ...current, exceptions: current.exceptions.map((item, itemIndex) => itemIndex === index ? { ...item, [key]: value } : item) } : current);
  const updateBranchDuration = (branchId: string, duration: number) => setConfig((current) => current ? { ...current, restaurant: { ...current.restaurant, branches: current.restaurant.branches.map((branch) => branch.id === branchId ? { ...branch, onlineBookingDurationMinutes: duration } : branch) } } : current);
  const save = async () => { setSaving(true); setError(""); try { const response = await fetch(`${API_URL}/restaurant/online-booking`, { method: "PUT", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify({ ...config.settings, branchDurations: config.restaurant.branches.map((branch) => ({ branchId: branch.id, durationMinutes: branch.onlineBookingDurationMinutes })), schedules: config.schedules, exceptions: config.exceptions }) }); if (!response.ok) throw new Error(await response.text() || "No se pudo guardar"); setConfig(await response.json()); } catch (reason) { setError(reason instanceof Error ? reason.message : "No se pudo guardar"); } finally { setSaving(false); } };
  return <WorkspaceShell title="Reservas online" description="Activa y configura la pagina publica para que tus clientes reserven sin iniciar sesion.">
    <section className="rounded-[26px] border border-brand-line bg-white p-5 md:p-7">
      <div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm font-semibold text-brand-ink">Habilitar reservas online</p><p className="mt-1 text-sm text-neutral-500">Publica el enlace para recibir reservas desde redes y QR.</p></div><button type="button" onClick={() => updateSettings("isEnabled", !config.settings.isEnabled)} className={`rounded-full px-5 py-3 text-sm font-bold ${config.settings.isEnabled ? "bg-brand-orange text-white" : "bg-neutral-200 text-neutral-600"}`}>{config.settings.isEnabled ? "Habilitadas" : "Deshabilitadas"}</button></div>
      <div className="mt-6 grid gap-4 lg:grid-cols-[1fr_auto]"><label className="space-y-2 text-sm font-medium"><span>Link publico</span><input readOnly value={publicUrl} className="foodie-input" /></label><div className="flex gap-2 self-end"><button type="button" onClick={() => navigator.clipboard.writeText(publicUrl)} className="rounded-full border border-brand-line px-4 py-3 text-brand-ink"><Copy className="h-4 w-4" /></button><a href={publicUrl} target="_blank" className="rounded-full bg-brand-orange px-4 py-3 text-white"><ExternalLink className="h-4 w-4" /></a></div></div>
      <div className="mt-7 grid gap-4 md:grid-cols-2"><label className="space-y-2 text-sm font-medium"><span>Imagen de portada (URL)</span><input value={config.settings.coverImageUrl || ""} onChange={(event) => updateSettings("coverImageUrl", event.target.value || null)} className="foodie-input" placeholder="https://..." /></label><label className="space-y-2 text-sm font-medium"><span>Color principal</span><input type="color" value={config.settings.accentColor} onChange={(event) => updateSettings("accentColor", event.target.value)} className="h-12 w-full rounded-[18px] border border-brand-line p-1" /></label><label className="space-y-2 text-sm font-medium md:col-span-2"><span>WhatsApp para atención personalizada</span><input value={config.settings.whatsappPhone || ""} onChange={(event) => updateSettings("whatsappPhone", event.target.value || null)} className="foodie-input" placeholder="+54 9 11 1234 5678" /><span className="block text-xs font-normal text-neutral-500">Este número se abre desde el botón público de atención personalizada.</span></label></div>
      <div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["minAdvanceMinutes", "Anticipacion minima (min)"], ["maxAdvanceDays", "Anticipacion maxima (dias)"], ["minPartySize", "Minimo de personas"], ["maxPartySize", "Maximo de personas"]].map(([key, label]) => <label key={key} className="space-y-2 text-sm font-medium"><span>{label}</span><input type="number" min="0" value={config.settings[key as keyof Config["settings"]] as number} onChange={(event) => updateSettings(key, Number(event.target.value))} className="foodie-input" /></label>)}</div>
    </section>
    <section className="rounded-[26px] border border-brand-line bg-white p-5 md:p-7"><h2 className="text-xl font-extrabold text-brand-ink">Horarios por sede</h2><p className="mt-1 text-sm text-neutral-500">Los horarios disponibles se validan contra la capacidad real de mesas.</p>{config.restaurant.branches.map((branch) => <div key={branch.id} className="mt-6 overflow-x-auto"><div className="mb-3 flex items-center justify-between gap-3"><h3 className="font-bold text-brand-ink">{branch.name}</h3><label className="flex items-center gap-2 text-sm font-semibold">Duración de reserva <input type="number" min="15" max="720" value={branch.onlineBookingDurationMinutes} onChange={(event) => updateBranchDuration(branch.id, Number(event.target.value))} className="foodie-input w-24 py-2" /> min</label></div><div className="min-w-[720px] divide-y divide-brand-line border-y border-brand-line">{days.map((day, weekday) => { const row = config.schedules.find((item) => item.branchId === branch.id && item.weekday === weekday)!; return <div key={day} className="grid grid-cols-[150px_80px_1fr_1fr_120px] items-center gap-3 py-3 text-sm"><span className="font-semibold">{day}</span><input type="checkbox" checked={row.isEnabled} onChange={(event) => updateSchedule(branch.id, weekday, "isEnabled", event.target.checked)} /><input type="time" value={row.startTime} onChange={(event) => updateSchedule(branch.id, weekday, "startTime", event.target.value)} className="foodie-input py-2" /><input type="time" value={row.endTime} onChange={(event) => updateSchedule(branch.id, weekday, "endTime", event.target.value)} className="foodie-input py-2" /><input type="number" value={row.intervalMin} min="5" onChange={(event) => updateSchedule(branch.id, weekday, "intervalMin", Number(event.target.value))} className="foodie-input py-2" title="Intervalo en minutos" /></div>; })}</div></div>)}</section>
    <section className="rounded-[26px] border border-brand-line bg-white p-5 md:p-7"><div className="flex items-center justify-between gap-4"><div><h2 className="text-xl font-extrabold text-brand-ink">Excepciones de fecha</h2><p className="mt-1 text-sm text-neutral-500">Cerrá una fecha o reemplazá su horario habitual.</p></div><button type="button" onClick={addException} className="rounded-full border border-brand-line px-4 py-2 text-sm font-bold text-brand-ink">Agregar fecha</button></div><div className="mt-5 space-y-3">{config.exceptions.map((item, index) => <div key={`${item.branchId}-${item.serviceDate}-${index}`} className="grid gap-3 rounded-2xl border border-brand-line p-3 md:grid-cols-[1fr_170px_110px_110px_110px_auto]"><select value={item.branchId} onChange={(event) => updateException(index, "branchId", event.target.value)} className="foodie-input py-2">{config.restaurant.branches.map((branch) => <option key={branch.id} value={branch.id}>{branch.name}</option>)}</select><input type="date" value={item.serviceDate} onChange={(event) => updateException(index, "serviceDate", event.target.value)} className="foodie-input py-2" /><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={item.isClosed} onChange={(event) => updateException(index, "isClosed", event.target.checked)} /> Cerrado</label>{!item.isClosed ? <><input type="time" value={item.startTime || "12:00"} onChange={(event) => updateException(index, "startTime", event.target.value)} className="foodie-input py-2" /><input type="time" value={item.endTime || "23:00"} onChange={(event) => updateException(index, "endTime", event.target.value)} className="foodie-input py-2" /></> : <div className="md:col-span-2" />}<button type="button" onClick={() => setConfig((current) => current ? { ...current, exceptions: current.exceptions.filter((_, itemIndex) => itemIndex !== index) } : current)} className="text-sm font-bold text-red-600">Quitar</button></div>)}</div></section>
    <div className="flex justify-end"><button type="button" disabled={saving} onClick={() => void save()} className="inline-flex items-center gap-2 rounded-full bg-brand-orange px-6 py-3 font-bold text-white"><Save className="h-4 w-4" />{saving ? "Guardando..." : "Guardar cambios"}</button></div>{error ? <p className="text-sm text-red-600">{error}</p> : null}
  </WorkspaceShell>;
}
