"use client";

import { Save } from "lucide-react";
import { useEffect, useState } from "react";
import { WorkspaceShell } from "./workspace-shell";
import { useWorkspace } from "./workspace-provider";

const API_URL = process.env.NEXT_PUBLIC_API_URL || "http://localhost:4000/v1";
type Config = { [key: string]: string | boolean | null | unknown[] | undefined; specials: unknown[]; description?: string | null; cuisineType?: string | null; address?: string | null; city?: string | null; province?: string | null; country?: string | null; phone?: string | null; email?: string | null; websiteUrl?: string | null; instagramUrl?: string | null; mapsUrl?: string | null; menuUrl?: string | null; whatsappPhone?: string | null; assistantEnabled?: boolean; assistantName?: string | null; assistantRole?: string | null; assistantLocale?: string | null; assistantTone?: string | null; assistantFirstGreeting?: string | null; assistantDisclosure?: boolean; humanSupportPhone?: string | null; humanSupportWhatsapp?: string | null; humanSupportEmail?: string | null };

const generalFields: Array<[keyof Config, string]> = [["description", "Descripción corta"], ["cuisineType", "Tipo de cocina"], ["address", "Dirección"], ["city", "Ciudad"], ["province", "Provincia"], ["country", "País"], ["phone", "Teléfono"], ["email", "Email"], ["websiteUrl", "Web"], ["instagramUrl", "Instagram"], ["mapsUrl", "Google Maps"], ["menuUrl", "Carta en Google Drive"], ["whatsappPhone", "WhatsApp"]];

export function PersonalizeRestaurantPage({ mode = "general" }: { mode?: "general" | "assistant" }) {
  const { token, currentUser } = useWorkspace(); const [config, setConfig] = useState<Config | null>(null); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  useEffect(() => { if (!token) return; fetch(`${API_URL}/restaurant/configuration/personalize`, { headers: { Authorization: `Bearer ${token}` } }).then(async (response) => { if (!response.ok) throw new Error("No se pudo cargar la configuración"); return response.json() as Promise<Config>; }).then(setConfig).catch((reason) => setError(reason.message)); }, [token]);
  if (currentUser?.role !== "restaurant_owner") return <WorkspaceShell title="Configuración" description="Información central del restaurante."><p>No tenés permiso para editar esta configuración.</p></WorkspaceShell>;
  if (!config) return <WorkspaceShell title="Configuración" description="Información central del restaurante."><p>{error || "Cargando configuración..."}</p></WorkspaceShell>;
  const update = (key: keyof Config, value: string | boolean | null) => setConfig((current) => current ? { ...current, [key]: value } : current);
  const save = async () => { setSaving(true); setError(""); try { const response = await fetch(`${API_URL}/restaurant/configuration/personalize`, { method: "PUT", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify(config) }); if (!response.ok) throw new Error("No se pudo guardar la configuración"); setConfig(await response.json()); } catch (reason) { setError(reason instanceof Error ? reason.message : "No se pudo guardar"); } finally { setSaving(false); } };
  const general = <section className="rounded-[26px] border border-brand-line bg-white p-5 md:p-7"><h2 className="text-xl font-extrabold text-brand-ink">Información del restaurante</h2><p className="mt-1 text-sm text-neutral-500">Estos datos son la fuente compartida para la web y el asistente.</p><div className="mt-5 grid gap-4 md:grid-cols-2">{generalFields.map(([key, label]) => <Field key={String(key)} label={label}><input value={String(config[key] || "")} onChange={(event) => update(key, event.target.value || null)} className="foodie-input" /></Field>)}</div></section>;
  const assistant = <section className="rounded-[26px] border border-brand-line bg-white p-5 md:p-7"><h2 className="text-xl font-extrabold text-brand-ink">Asistente virtual</h2><p className="mt-1 text-sm text-neutral-500">Foodie mantiene las reglas críticas; acá configurás la identidad del asistente. Para derivaciones humanas se usan los datos de contacto cargados en General.</p><div className="mt-5 grid gap-4 md:grid-cols-2"><Toggle label="Asistente habilitado" value={config.assistantEnabled ?? true} onChange={(value) => update("assistantEnabled", value)} /><Toggle label="Indicar que es asistente virtual" value={config.assistantDisclosure ?? true} onChange={(value) => update("assistantDisclosure", value)} /><Field label="Nombre"><input value={String(config.assistantName || "")} onChange={(event) => update("assistantName", event.target.value || null)} className="foodie-input" /></Field><Field label="Rol"><input value={String(config.assistantRole || "")} onChange={(event) => update("assistantRole", event.target.value || null)} className="foodie-input" /></Field><Field label="Idioma / locale"><input value={String(config.assistantLocale || "es-AR")} onChange={(event) => update("assistantLocale", event.target.value || null)} className="foodie-input" /></Field><Field label="Tono"><input value={String(config.assistantTone || "calido_breve_profesional")} onChange={(event) => update("assistantTone", event.target.value || null)} className="foodie-input" /></Field><div className="md:col-span-2"><Field label="Saludo inicial"><textarea value={String(config.assistantFirstGreeting || "")} onChange={(event) => update("assistantFirstGreeting", event.target.value || null)} className="foodie-input min-h-24" /></Field></div></div></section>;
  return <WorkspaceShell title={mode === "assistant" ? "Asistente virtual" : "General"} description="Configuración centralizada para Foodie, web pública y n8n."><div className="space-y-6">{mode === "assistant" ? assistant : general}<div className="flex justify-end"><button type="button" disabled={saving} onClick={() => void save()} className="inline-flex items-center gap-2 rounded-full bg-brand-orange px-6 py-3 font-bold text-white"><Save className="h-4 w-4" />{saving ? "Guardando..." : "Guardar cambios"}</button></div>{error ? <p className="text-sm font-semibold text-red-600">{error}</p> : null}</div></WorkspaceShell>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block space-y-2 text-sm font-semibold text-brand-ink"><span>{label}</span>{children}</label>; }
function Toggle({ label, value, onChange }: { label: string; value: boolean; onChange: (value: boolean) => void }) { return <label className="flex items-center gap-3 rounded-2xl border border-brand-line px-4 py-3 text-sm font-bold text-brand-ink"><input type="checkbox" checked={value} onChange={(event) => onChange(event.target.checked)} />{label}</label>; }
